---
title: "Call for SIG Officer Nominations"
author: ""
date: 2024-10-04
categories: ["Business"]
tags: ["SIG", "AERA"]
editor_options: 
  markdown: 
    wrap: 72
---

Our Systematic Review and Meta-Analysis SIG is seeking new officers for the leadership team, with terms starting after the end of the 2025 convention next April. We welcome nominations (including self-nominations!) for any of the following positions:

- Program Chair – organizes and manages the proposal review process and assembles the SIG’s program for the annual convention.
- Secretary – reports on SIG activities, including the annual business meeting, and leads communications with SIG members.
- Treasurer – manages and reports on SIG financial accounts, approves any expenditures.
- Graduate student member-at-large – engages with graduate students around SIG activities, provides input and represents student perspectives on SIG activities.

Per the SIG bylaws, our current program co-chairs, Carlton Fong and Derek Rodgers, will be stepping into the role of SIG co-chairs. If you are interested in running for any of the open positions, please contact James Pustejovsky no later than October 20th, 2024.
 
Getting involved as a SIG officer is a great way to contribute to our community. For most positions, the duties are light and the time commitment is low and flexible. The program chair responsibilities do require a bit more time and effort, mostly during Summer and early Fall, but the position also offers a meaningful and fulfilling way to shape our community’s priorities and direction. Program chair responsibilities can also be split between two co-chairs, so you are welcome to run with a buddy. If you have questions or are interested in learning more about any of the positions, please feel free to reach out to any of ther [current SIG officers](/leadership/). You can also read more about the official responsibilities of each position in our [SIG bylaws](/about/srma_bylaws.pdf).
