---
title: "New Officers for 2025-2027"
author: "James E. Pustejovsky"
date: 2025-04-10
categories: ["Business"]
tags: ["SIG", "AERA"]
editor_options: 
  markdown: 
    wrap: 72
---

This past Winter, AERA once again held officer elections for all of its Special Interest Groups and Divisions. I'm excited that we will have some fresh faces on SRMA SIG's leadership team starting after the AERA convention this month, as well as some familiar faces stepping into new roles. Officers for the 2025-2027 term will be:

* [Carlton Fong](https://faculty.txst.edu/profile/2018070) (Texas State University) and [Derek Rodgers](https://iowareadingresearch.org/person/derek-rodgers) (University of Iowa) will be taking the helm as SIG co-chairs, after completing their term as program co-chairs.
* [Amanda Neitzel](https://schoolhealth.jhu.edu/staff/amanda-neitzel-phd/) (Johns Hopkins University) and [Mariola Moeyaert](https://www.albany.edu/education/faculty/mariola-moeyaert) (University at Albany, State University of New York) will be taking charge of conference organizing activities as program co-chairs.
*	[Bixi Zhang](https://www.gc.cuny.edu/people/bixi-zhang) (The Graduate Center, City University of New York) will be joining the leadership team as secretary.
*	[Jihyun Lee](https://coe.unt.edu/people/jihyun-lee.html) (University of North Texas) will be stepping in as treasurer.
* [Xue Wang](https://education.jhu.edu/phd-students/xue-wang/) (Johns Hopkins University) will be serving as our graduate student representative-at-large. 

Congratulations and thanks to our new officers for your willingness to serve! I am looking forward to seeing the new ideas and energy you will bring to our community. 